### ISSUE TITLE
NavList font size different on different pages

### ISSUE THREAD

**Issue by martypowell** [martypowell/baltimorecountymd.gov-assets#1]
Font size is not consistent on all pages, even if they are using the same template.

***Examples***
* https://staging.baltimorecountymd.gov/homepageredesign/
* http://staging.baltimorecountymd.gov/homepageredesign/imlooking/index.html#all

**Comment by martypowell** [comment]
Can one of you two verify this now?

**Comment by sdurphy** [comment]
the first link is broken... do you want us to compare to the homepage?

**Comment by martypowell** [comment]
The first page may be broken, but it showed the behavior of the navList being different sizes.

**Comment by martypowell** [comment]
Confirmed

**Comment by martypowell** [comment]
Evident on this page http://staging.baltimorecountymd.gov/homepageredesign/Agencies/publicworks/SnowFighter/Snow%20Removal/snowremoval.html

**Comment by martypowell** [comment]
Issue ending up being with the template and not the code.

**Comment by sdurphy** [comment]
Is there a reason why the In This Section navigation disappears at mobile size?
