### ISSUE TITLE
Snowfighter Most Requested font too large

### ISSUE THREAD

**Issue by danfox01** [martypowell/baltimorecountymd.gov-assets#5]
http://staging.baltimorecountymd.gov/homepageredesign/Agencies/publicworks/SnowFighter/index.html

![image](https://cloud.githubusercontent.com/assets/13049389/8357198/a1214902-1b27-11e5-899f-915b9b750ec0.png)

**Comment by martypowell** [comment]
Duplicate of #1

**Comment by martypowell** [comment]
Fixed in issue #1
