### ISSUE TITLE
Heading sizes are small on new template than old ones (mobile)

### ISSUE THREAD

**Issue by danfox01** [martypowell/baltimorecountymd.gov-assets#7]
H1's and H2's should be larger -- easier to scan.

Example: http://staging.baltimorecountymd.gov/homepageredesign/Agencies/health/petadoption/index.html
vs.
http://www.baltimorecountymd.gov/Agencies/health/petadoption/index.html?semobipref=true

I'd like to get sam's input on sizes as well.

**Comment by martypowell** [comment]
Dan, the h1's are identical sizes on each page?  Are you seeing something different?

**Comment by sdurphy** [comment]
Dan are you wearing the wrong contacts again?

**Comment by danfox01** [comment]
Sam, remember when you kept saying the homepage images were blurry and no one believed you? Let me grab some screens...

**Comment by sdurphy** [comment]
Oh wait... I just looked again. Looks like the h2's and h3's are too small

**Comment by danfox01** [comment]
New template:

![image](https://cloud.githubusercontent.com/assets/13049389/8360987/54ed4ca4-1b3e-11e5-8fc8-1b15be4f2862.png)

Old template:

![image](https://cloud.githubusercontent.com/assets/13049389/8361019/8706f0f0-1b3e-11e5-8bed-ccdd31db2efe.png)

**Comment by sdurphy** [comment]
Hey Marty,

Heading sizes should be as follows:

h1 {font-size:1.8em;}
h2 {font-size:1.3em;}
h3 {font-size:1.1em;}
h4 {font-size: 1em;}
h5 {font-size: .9em;}
h6 {font-size: .7em;}

**Comment by martypowell** [comment]
Changes made, can you please confirm? http://staging.baltimorecountymd.gov/homepageredesign/Agencies/health/petadoption/index.html
