### ISSUE TITLE
Promoter/image caption should be below image in responsive

### ISSUE THREAD

**Issue by danfox01** [martypowell/baltimorecountymd.gov-assets#9]
Noticed this in the CHART module for snowfighter. Not sure where else it might happen.

![image](https://cloud.githubusercontent.com/assets/13049389/8363230/9d081534-1b4b-11e5-8b75-6a472ec58f5f.png)

**Comment by martypowell** [comment]
Link?  mobile or desktop?

**Comment by danfox01** [comment]
Sorry, mobile size: http://staging.baltimorecountymd.gov/homepageredesign/Agencies/publicworks/SnowFighter/index.html/
